stages:
  - build
  - test
  - package

.python: &python-job
  image: python:3.6
  tags:
    - runner:k8s

  before_script:
    - pip3 install -r requirements.txt

build:python:
  <<: *python-job
  stage: build

  script:
    - python -OO -m py_compile hollow.py
  artifacts:
    expire_in: 1 hour
    paths:
      - src

test:python:
  <<: *python-job
  stage: test

  dependencies:
    - build:python
  script:
    - ./hollow.py -h

package:docker:
  stage: package
  image: docker:stable
  services:
    - docker:stable-dind
  tags:
    - runner:k8s

  dependencies:
    - build:python
  before_script:
    - mkdir /root/.docker
    - ln -s /secrets/docker /root/.docker/config.json
    - docker info
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    IMAGE_TAG: ssube/hollow-yaml:$CI_COMMIT_REF_SLUG